

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: global  
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default 
  source: 
    path: helm
    repoURL: https://github.com/ltelen/argocrd-test.git
    targetRevision: HEAD
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  syncPolicy: 
    automated: 
      selfHeal: true
      prune:  true
