apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default 
  source: 
    path: helm
    repoURL: https://github.com/ltelen/test-app.git
    targetRevision: HEAD
    api:
      values: |
        image: 
          tag: latest
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  syncPolicy: 
    automated: 
      selfHeal: true
      prune:  true
